### ISSUE TITLE
add options for other test frameworks

### ISSUE THREAD

**Issue by bucaran** [iamstarkov/generator-tiny-es-nm#6]
For example, [`tape`](https://github.com/substack/tape) :smile: 

Doable?

**Comment by iamstarkov** [comment]
its sure doable

Im not into `tape`, can you describe benefits over mocha+assert?

**Comment by bucaran** [comment]
It's much more limited compared to Mocha. It's also smaller, lighter and more self-contained. `equal` and `deepEqual` is usually all you need to get stuff done. Also no globals. 

I have nothing against Mocha. But I prefer the simplicity model favored by tape.

**Comment by iamstarkov** [comment]
hmm, looks interesting. can you show some your projects with tape tests?

**Comment by bucaran** [comment]
[Parsec](https://github.com/bucaran/parsec/blob/master/test/index.js)
[Fly](https://github.com/flyjs/fly)

**Comment by iamstarkov** [comment]
im almost sold. last question what tool are using for coverage? cannot see anything https://github.com/bucaran/parsec/blob/master/package.json#L6-L12

**Comment by bucaran** [comment]
There does not seem to be a straightforward way for that. So, I guess this feat req is dead. :disappointed_relieved:

**Comment by iamstarkov** [comment]
its not dead, simply need more lurking, googling and stackoverflowing on the theme "tape coverage"

**Comment by bucaran** [comment]
I did, that's why I only replied after 15 minutes.

**Comment by iamstarkov** [comment]
there is a post by substack about tape and coverage:
http://substack.net/how_I_write_tests_for_node_and_the_browser
and here is a tool https://www.npmjs.com/package/covert

**Comment by bucaran** [comment]
Look what I [found](https://github.com/isaacs/node-tap#coverage). So, `node-tap`, is essentially the same thing.

**Comment by iamstarkov** [comment]
looks good, will try it out

**Comment by bucaran** [comment]
Yeah, me too. And update my crappy generator as well. I think this generator will be my goto for big projects, but I'll use pizza for stuff like tiny modules. In fact, I registered [this](https://www.npmjs.com/package/generator-es-nm), but if you want it I can release it for you and maybe you could release `tiny-es-nm` to me.

**Comment by iamstarkov** [comment]
wat? i didnt follow you. your last message has been changed

**Comment by bucaran** [comment]
I thought about exchanging module _names_, as I believe your `tiny-es-nm` is not really tiny at all, but very complete and thorough. But then I thought about what a PITA it would be to do this, so I said nevermind.

**Comment by iamstarkov** [comment]
okay. anyway, i thinkg it still very tiny, because it asks as few question as possible, and shipped as small number of files as possible. It even dont shipped with eslintrc

**Comment by bucaran** [comment]
You are right. I would love to use this module, but there are few bits I would like to discuss and definitely support node-tap or tape. Do you mind if I attempt to add tape support?

**Comment by iamstarkov** [comment]
im not in love with adding a new question, but good news, if tape will give ability to test, coverage and es6, then I prefer to replace mocha to tape. So, you are welcome with tape support.

**Comment by iamstarkov** [comment]
im definetily will wait for this

**Comment by iamstarkov** [comment]
primarily because im also dont like mocha globals

**Comment by bucaran** [comment]
OK, I will give it a shot tonight! :smile:

**Comment by bucaran** [comment]
Ok, I'm working on this. I should be done in a few hours or minutes :smile: 

I will use `tap` for the generator's test as well.

**Comment by iamstarkov** [comment]
Awesome 

> I will use tap for the generator's test as well

well done, we should eat our own dog food

**Comment by bucaran** [comment]
Indeed.

**Comment by bucaran** [comment]
@iamstarkov BTW I didn't disappear. It has been incredibly difficult to pull all this together using `tape`, Babel and coveralls. But I am almost there. Hang on tight.

**Comment by iamstarkov** [comment]
apparently, this issue can be closed =)
