### ISSUE TITLE
Add url to the repo

### ISSUE THREAD

**Issue by bucaran** [iamstarkov/generator-tiny-es-nm#7]
I generated this URL for you, hope you are OK with it
+ http://git.io/tiny-es-nm

**Comment by iamstarkov** [comment]
already done =)

**Comment by iamstarkov** [comment]
btw, how do you create this short urls? https://git.io/ dont allow me to create ones with custom names

**Comment by bucaran** [comment]
Usually people have to send me an email. Just kidding → git.io

**Comment by iamstarkov** [comment]
yeah, i tried to shorter https://github.com/jgm/commonmark.js/ to some readable url, but got only http://git.io/vscCs. what im doing wrong?

**Comment by bucaran** [comment]
You are out of luck. Once you generate the tiny url you can't remove it (unless you concat GitHub support and ask nicely about it).
