### ISSUE TITLE
No semicolons

### ISSUE THREAD

**Issue by bucaran** [iamstarkov/generator-tiny-es-nm#8]
Do you have strong opinions regarding semicolons or are you willing to change your mind regarding this issue?

I can summarize for you if you wish so, but [this](http://blog.izs.me/post/2353458699/an-open-letter-to-javascript-leaders-regarding) is always a good read.

Up to you.

**Comment by iamstarkov** [comment]
i have seen that post in the past, but its worth to read it again, thank you.

I understand, how to use them. Have no strong opinion though and [love to experiment](https://github.com/iamstarkov/get-md-image/blob/master/test.js#L9-L19)

**Comment by bucaran** [comment]
I'm glad. 

>  love to experiment

:+1: 

To give you an example of a project that does not use semicolons, there's `npm`.

**Comment by iamstarkov** [comment]
Sindre Sorhus answered the best sindresorhus/ama#84:

> In the end, semi-colons are like indentation, no actual correct answer, just strong opinions. Pick whatever you prefer and use the existing style when contributing.

**Comment by bucaran** [comment]
So you would like to keep them in the project or can I remove them?

**Comment by iamstarkov** [comment]
if you dont mind, ill prefer to keep current state of the things. Or remove them if you want.

Contributions are better than semicolons, after all =)
